<?php

declare(strict_types=1);

namespace VL\LMS\Admin\MetaBoxes;

use WP_Post;
use WP_User;

/**
 * "Автор курсу" / "Автор вебінару" meta-box.
 *
 * Side-column UI for changing the lead instructor of a `vl_course` or
 * `vl_webinar`, which the domain stores as plain `post_author` (see
 * {@see \VL\LMS\Services\CourseInstructors\AuthorSyncService}, which
 * mirrors it into the `vl_course_instructors` lead row for both entity
 * types). Core's own `authordiv` would technically do this, but it hides
 * behind Screen Options and is not part of the Ukrainian admin vocabulary
 * — so `AdminProvider` removes it and this box takes its place, offering
 * the same capability-based candidate pool authordiv would.
 *
 * Instantiated once per supported post type (mirroring the per-parent
 * child-list boxes) rather than subclassed per type — only the title and
 * box id vary.
 *
 * The select reuses core's `post_author_override` field name on purpose:
 * `edit_post()` → `_wp_translate_postdata()` consumes it, enforces the
 * post type's `edit_others_*` primitive, and writes `post_author` before
 * any `save_post` listener runs — which is what lets `AuthorSyncService`
 * see the new author and reconcile the instructors table in the same save
 * pass. That is also why {@see self::save()} is a deliberate no-op.
 *
 * Editors without the `edit_others_*` primitive (instructors — both caps
 * are administrator-only by design) get a read-only view of the current
 * author instead of the select.
 *
 * @author Tymofii Synianskyi
 */
class AuthorMetaBox extends AbstractMetaBox {

	public function id(): string {
		return 'vl_webinar' === $this->post_type() ? 'vl_lms_webinar_author' : 'vl_lms_course_author';
	}

	public function title(): string {
		if ( 'vl_webinar' === $this->post_type() ) {
			return __( 'Автор вебінару', 'vl-lms' );
		}
		return __( 'Автор курсу', 'vl-lms' );
	}

	public function context(): string {
		return 'side';
	}

	public function priority(): string {
		return 'high';
	}

	public function render( WP_Post $post ): void {
		$author_id        = (int) $post->post_author;
		$post_type_object = get_post_type_object( $post->post_type );

		if ( null === $post_type_object || ! current_user_can( $post_type_object->cap->edit_others_posts ) ) {
			$this->render_current_author_readonly(
				$author_id,
				__( 'Змінити автора може адміністратор', 'vl-lms' )
			);
			return;
		}

		$dropdown = (string) wp_dropdown_users(
			[
				'name'             => 'post_author_override',
				'id'               => 'vl-lms-author',
				'selected'         => $author_id,
				// Keep the current author listed even when they can no
				// longer edit this post type, so an untouched form never
				// reassigns the post silently.
				'include_selected' => true,
				// The pool core's own authordiv offers since WP 5.9:
				// everyone capable of editing this post type (instructors +
				// administrators under CapabilitiesMap). A role-name filter
				// would silently empty the select on sites whose authors
				// hold the caps through a different role.
				'capability'       => [ $post_type_object->cap->edit_posts ],
				'show'             => 'display_name_with_login',
				'echo'             => false,
			]
		);

		if ( '' === $dropdown ) {
			// wp_dropdown_users() renders nothing at all when its query
			// matches no users — surface the state instead of a dead box.
			$this->render_current_author_readonly( $author_id, null );
			$this->render_inline_notice(
				__( 'Немає користувачів із правом редагувати цей тип записів — нікого запропонувати як автора.', 'vl-lms' )
			);
			return;
		}

		echo '<div class="vl-lms-row vl-lms-row--full">';
		printf(
			'<label for="vl-lms-author">%s</label>',
			esc_html__( 'Автор (головний інструктор)', 'vl-lms' )
		);
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Markup generated by wp_dropdown_users().
		echo $dropdown;
		echo '</div>';
		printf(
			'<p class="description">%s</p>',
			esc_html__( 'Попередній автор залишиться в команді як ко-інструктор.', 'vl-lms' )
		);
	}

	/**
	 * Deliberate no-op — see the class docblock. Persistence belongs to
	 * core's `post_author_override` handling; writing `post_author` here
	 * as well would be a second, later write racing the same field.
	 */
	public function save( int $post_id, WP_Post $post ): void {
		unset( $post_id, $post );
	}

	private function render_current_author_readonly( int $author_id, ?string $hint ): void {
		$author = get_userdata( $author_id );
		$this->render_readonly_row(
			__( 'Автор', 'vl-lms' ),
			$author instanceof WP_User ? $author->display_name : '',
			$hint
		);
	}
}
